locals {
  config_dir  = "${var.project_root}/config"
  secrets_dir = "${var.project_root}/secrets"
  reports_dir = "${var.project_root}/reports"

  generated_at = timestamp()

  app_config_content = <<-EOT
    # Generated by Terraform - do not edit by hand
    # Base template used: ${data.local_file.app_template.filename}
    app_name    = "${var.app_name}"
    environment = "${var.environment}"
    port        = ${var.app_port}
  EOT

  database_config_content = <<-EOT
    # Generated by Terraform - do not edit by hand
    db_name     = "${var.db_name}"
    db_user     = "${var.db_user}"
    db_host     = "localhost"
    db_port     = 5432
  EOT
}
