# Base template for application configuration files. 
# This file is committed to the repo and read at plan/apply time 
# via a `data "local_file"` data source — it is NOT generated by Terraform. 
# Format: key = value EOF